name: findjackpots
region: nyc
services:
- name: web
  github:
    repo: jasonmorrow123/findjackpots
    branch: main
    deploy_on_push: true
  run_command: node server.js
  environment_slug: node-js
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 3000
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
  - key: VAPID_PUBLIC_KEY
    value: BB8gaqvbK6lH-aVul2FkGAIH9nbdKagdOuLLpSC5y4JhUb1j2OS-jqMV4rqTcKdClepKQi0ylIhEGlkQvmC0u4E
    scope: RUN_TIME
  - key: VAPID_PRIVATE_KEY
    scope: RUN_TIME
    type: SECRET
  - key: MIGRATE_SECRET
    scope: RUN_TIME
    type: SECRET
